import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

import { Merriweather_Sans, Work_Sans } from "next/font/google";
const workSans = Work_Sans({
  weight: ["100", "200", "300", "400", "500", "800", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-heading",
});

const merriweather = Merriweather_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${merriweather.variable} antialiased`}
      >
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
